# Generated by Django 2.0 on 2017-12-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='jissueno',
            field=models.IntegerField(blank=True, verbose_name='Issue No'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jpageno',
            field=models.CharField(blank=True, max_length=20, verbose_name='Page No'),
        ),
    ]
