# Generated by Django 2.0 on 2017-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0002_auto_20171212_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='jissn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISSN NO'),
        ),
    ]
