# Generated by Django 2.0 on 2017-12-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testmodelresapp', '0003_auto_20171212_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refformat', models.TextField(max_length=500, verbose_name='Citation Format')),
                ('booktitle', models.CharField(default='', max_length=200, verbose_name='Paper Title')),
                ('bookname', models.CharField(default='', max_length=200, verbose_name='Conference Name')),
                ('pubfromconf', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50, verbose_name='Through conf.')),
                ('bsjr', models.FloatField(blank=True, verbose_name='SJR')),
                ('bsnip', models.FloatField(blank=True, verbose_name='SJR')),
                ('bisbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN NO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
                ('facultyauthor', models.ManyToManyField(max_length=100, to='testmodelresapp.Faculty', verbose_name='Faculty Author')),
                ('rsauthor', models.ManyToManyField(blank=True, max_length=100, to='testmodelresapp.ResearchScholar', verbose_name='Research Scholar Author')),
                ('studentauthor', models.ManyToManyField(blank=True, max_length=100, to='testmodelresapp.Student', verbose_name='Student Author')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refformat', models.TextField(max_length=500, verbose_name='Citation Format')),
                ('ctitle', models.CharField(default='', max_length=200, verbose_name='Paper Title')),
                ('cname', models.CharField(default='', max_length=200, verbose_name='Conference Name')),
                ('presentedby', models.CharField(max_length=50, verbose_name='Presented By')),
                ('conferencecategory', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='International', max_length=50, verbose_name='Conference Category')),
                ('cdatefrom', models.DateField(verbose_name='Conference Date From: ')),
                ('cdateto', models.DateField(verbose_name='Conference Date To: ')),
                ('venue', models.CharField(max_length=100, verbose_name='Venue')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('csjr', models.FloatField(blank=True, verbose_name='SJR')),
                ('csnip', models.FloatField(blank=True, verbose_name='SNIP')),
                ('cisbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN NO')),
                ('pubtojournalorbook', models.CharField(choices=[('No', 'No'), ('Journal', 'Journal'), ('Book Series', 'Book Series')], default='No', max_length=50, verbose_name='To be Published as Journal/ Book')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to=settings.AUTH_USER_MODEL)),
                ('facultyauthor', models.ManyToManyField(max_length=100, to='testmodelresapp.Faculty', verbose_name='Faculty Author')),
                ('rsauthor', models.ManyToManyField(blank=True, max_length=100, to='testmodelresapp.ResearchScholar', verbose_name='Research Scholar Author')),
                ('studentauthor', models.ManyToManyField(blank=True, max_length=100, to='testmodelresapp.Student', verbose_name='Student Author')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=200, verbose_name='Project Title')),
                ('fundingagency', models.CharField(max_length=200, verbose_name='Funding Agency')),
                ('projectcategory', models.CharField(choices=[('External', 'External'), ('Internal Faculty', 'Internal Faculty'), ('Internal Student', 'Internal Student')], default='External', max_length=50, verbose_name='Project Category')),
                ('projectstatus', models.CharField(choices=[('Submitted', 'Submitted'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Presented-Results Awaiting', 'Presented-Results Awaiting')], default='Ongoing', max_length=50, verbose_name='Project Category')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('sanctioneddate', models.DateField(max_length=50, verbose_name='Sanctioned Date')),
                ('sanctionedamount', models.FloatField(blank=True, verbose_name='Sanctioned Amount')),
                ('fundreleasedon', models.DateField(blank=True, verbose_name='Fund Released On')),
                ('amountreceived', models.CharField(blank=True, max_length=200, verbose_name='Amount Received')),
                ('completiondate', models.DateField(blank=True, verbose_name='Completion Date')),
                ('outcome', models.TextField(blank=True, max_length=500, verbose_name='Outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(null=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('facultycopi', models.ManyToManyField(blank=True, related_name='projectcopis', to='testmodelresapp.Faculty', verbose_name='Principal Investigator')),
                ('facultypi', models.ManyToManyField(blank=True, related_name='projectpis', to='testmodelresapp.Faculty', verbose_name='Faculty')),
                ('rs', models.ManyToManyField(blank=True, max_length=100, to='testmodelresapp.ResearchScholar', verbose_name='Research Scholar')),
                ('student', models.ManyToManyField(blank=True, max_length=100, to='testmodelresapp.Student', verbose_name='Student')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jissueno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Issue No'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jpageno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Page No'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jvolno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='refformat',
            field=models.TextField(max_length=500, verbose_name='Citation Format'),
        ),
    ]
