# Generated by Django 2.0 on 2017-12-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0004_auto_20171212_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='jpublishedon',
            field=models.DateTimeField(blank=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Updated At'),
        ),
    ]
