# Generated by Django 2.0 on 2017-12-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0005_auto_20171213_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='jissn',
            field=models.CharField(default='No', max_length=20, verbose_name='ISSN NO'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jsjr',
            field=models.FloatField(default='0.0', verbose_name='SJR'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jsnip',
            field=models.FloatField(default='0.0', verbose_name='SNIP'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jtr',
            field=models.FloatField(default='0.0', verbose_name='SCI-IF'),
        ),
    ]
