# Generated by Django 2.0 on 2017-12-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0006_auto_20171214_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='jtr',
            field=models.FloatField(null=True, verbose_name='SCI-IF'),
        ),
    ]
