# Generated by Django 2.0 on 2017-12-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0007_auto_20171214_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='jtr',
            field=models.FloatField(blank=True, null=True, verbose_name='SCI-IF'),
        ),
    ]
