# Generated by Django 2.0 on 2017-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0008_auto_20171214_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='jsjr',
            field=models.FloatField(default=0.0, verbose_name='SJR'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jsnip',
            field=models.FloatField(default=0.0, verbose_name='SNIP'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jtr',
            field=models.FloatField(default=0.0, verbose_name='SCI-IF'),
        ),
    ]
