# Generated by Django 2.0 on 2017-12-14 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0011_auto_20171214_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseries',
            name='bpublishedon',
            field=models.DateField(default=datetime.date.today, verbose_name='Publication on:'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='bisbn',
            field=models.FloatField(blank=True, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='bsjr',
            field=models.FloatField(blank=True, null=True, verbose_name='SJR'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='bsnip',
            field=models.FloatField(blank=True, null=True, verbose_name='SNIP'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='facultyauthor',
            field=models.ManyToManyField(to='testmodelresapp.Faculty', verbose_name='Faculty Author'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='rsauthor',
            field=models.ManyToManyField(blank=True, to='testmodelresapp.ResearchScholar', verbose_name='Research Scholar Author'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='studentauthor',
            field=models.ManyToManyField(blank=True, to='testmodelresapp.Student', verbose_name='Student Author'),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='cisbn',
            field=models.FloatField(blank=True, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='csjr',
            field=models.FloatField(blank=True, null=True, verbose_name='SJR'),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='csnip',
            field=models.FloatField(blank=True, null=True, verbose_name='SNIP'),
        ),
        migrations.AlterField(
            model_name='conferencearticle',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='jpublishedon',
            field=models.DateField(blank=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completiondate',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fundreleasedon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fund Released On'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectstatus',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Results Pending', 'Results Pending'), ('Rejected', 'Rejected')], default='Ongoing', max_length=50, verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rs',
            field=models.ManyToManyField(blank=True, to='testmodelresapp.ResearchScholar', verbose_name='Research Scholar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sanctioneddate',
            field=models.DateField(verbose_name='Sanctioned Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ManyToManyField(blank=True, to='testmodelresapp.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Updated At'),
        ),
    ]
