# Generated by Django 2.0 on 2017-12-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0012_auto_20171214_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='facultycopi',
            field=models.ManyToManyField(blank=True, related_name='projectcopis', to='testmodelresapp.Faculty', verbose_name='Co-Principal Investigator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='facultypi',
            field=models.ManyToManyField(blank=True, related_name='projectpis', to='testmodelresapp.Faculty', verbose_name='Principal Investigator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentcategory',
            field=models.CharField(choices=[('UG Student', 'UG Student'), ('PG Student', 'PG Student')], default='UG Student', max_length=20, verbose_name='Student Category'),
        ),
    ]
