# Generated by Django 2.0 on 2017-12-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0013_auto_20171214_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectstatus',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Results Pending', 'Results Pending'), ('Rejected', 'Rejected')], default='Ongoing', max_length=50, verbose_name='Project Status'),
        ),
    ]
