# Generated by Django 2.0 on 2017-12-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0014_auto_20171214_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseries',
            name='bookname',
            field=models.CharField(default='', max_length=200, verbose_name='Book Title'),
        ),
    ]
