# Generated by Django 2.0 on 2017-12-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0015_auto_20171220_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalarticle',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Country, published from'),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='paynopay',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Pay-Non Paid'),
        ),
    ]
