# Generated by Django 2.0 on 2017-12-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelresapp', '0016_auto_20171220_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalarticle',
            name='paynopay',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, verbose_name='Paid Journal'),
        ),
    ]
